[phases.setup]
nixPkgs = ["python311", "gcc", "openssl"]

[phases.install]
cmds = [
  "python3.11 -m pip install --upgrade pip",
  "python3.11 -m pip install pydantic-core==2.14.6 --only-binary=:all: --python-version 3.11",
  "python3.11 -m pip install -r requirements.txt --only-binary=:all:"
]

[start]
cmd = "python3.11 bot.py"
